version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - BASE_URL=http://web:8000
    volumes:
      - .:/app

  redis:
    image: redis:alpine
    container_name: redis_broker
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_worker
    restart: always
    depends_on:
      - web
      - redis
    env_file:
      - .env
    environment:
      - BASE_URL=http://web:8000
    volumes:
      - .:/app
